from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Any, Callable, Iterable, Protocol, Sequence

from qlda.domain.models import ProjectScope

ProgressFn = Callable[[int, str, str], None]
CancelFn = Callable[[], bool]


class SessionPort(Protocol):
    def current_user(self, token: str) -> dict[str, Any]: ...


class ProjectAccessPort(Protocol):
    def require_project(self, user: dict[str, Any], project_id: int) -> ProjectScope: ...
    def require_project_code(self, user: dict[str, Any], project_code: str) -> ProjectScope: ...


class FilePort(Protocol):
    def local_path(self, file_id: str) -> tuple[dict[str, Any], Path]: ...
    def info(self, token: str, file_id: str) -> dict[str, Any]: ...
    def list_record_files(self, token: str, **kwargs: Any) -> dict[str, Any]: ...
    def record_file_counts(self, token: str, **kwargs: Any) -> dict[str, Any]: ...
    def save_bytes(self, token: str, **kwargs: Any) -> dict[str, Any]: ...
    def make_upload_ticket(self, token: str, **kwargs: Any) -> dict[str, Any]: ...
    def trash(self, token: str, file_id: str) -> dict[str, Any]: ...


class JobPort(Protocol):
    def ensure_schema(self) -> None: ...
    def build_upload_purpose(self, job_type: str, project_id: int, **options: Any) -> str: ...
    def parse_upload_purpose(self, value: str): ...
    def enqueue(self, **kwargs: Any): ...
    def enqueue_from_upload_purpose(self, upload_purpose: str, *, file_id: str, created_by: str = ""): ...
    def list(self, project_id: int, *, job_type: str = "", limit: int = 10): ...
    def get(self, job_id: int): ...
    def claim_next(self, worker_id: str): ...
    def request_cancel(self, job_id: int): ...
    def cancel_requested(self, job_id: int) -> bool: ...
    def update_progress(self, job_id: int, progress: int, stage: str, current_sheet: str = ""): ...
    def complete(self, job_id: int, result: dict[str, Any] | None = None): ...
    def fail(self, job_id: int, error_message: str, *, retry: bool = False): ...
    def recover_stale(self, *, stale_minutes: int = 20) -> int: ...
    def resource_limits(self): ...
    def memory_used_percent(self) -> float: ...
    def queue_stats(self): ...
    def heartbeat(self, worker_id: str, *, status: str, current_job_id: int | None = None): ...


class AIPort(Protocol):
    def ask(
        self,
        project_id: int,
        question: str,
        *,
        provider: str = "openai",
        history: Sequence[dict[str, Any]] | None = None,
        status_date: date | None = None,
        use_web: bool | None = None,
        workspace_scope: int | None = None,
    ) -> str: ...
    def schedule_risk(self, project_id: int, **kwargs: Any) -> str: ...
    def draft_report(self, project_id: int, **kwargs: Any) -> str: ...
    def legal_qa(self, project_id: int, question: str, **kwargs: Any) -> str: ...
    def test_connection(self, *, provider: str = "openai") -> str: ...


class SearchPort(Protocol):
    def search(
        self,
        project_id: int,
        query: str,
        *,
        kinds: Iterable[str] | None = None,
        limit: int = 50,
    ) -> list[dict[str, Any]]: ...


class ExcelImportPort(Protocol):
    def scan_workbook(
        self,
        path: str | Path,
        *,
        progress: ProgressFn | None = None,
        cancelled: CancelFn | None = None,
    ) -> dict[str, Any]: ...
    def process_job(
        self,
        job: dict[str, Any],
        path: str | Path,
        file_row: dict[str, Any],
        *,
        progress: ProgressFn | None = None,
        cancelled: CancelFn | None = None,
    ) -> dict[str, Any]: ...
