[server]
headless = true
maxUploadSize = 200
enableXsrfProtection = true
fileWatcherType = "none"
runOnSave = false

[runner]
fastReruns = true

[browser]
gatherUsageStats = false

[logger]
level = "warning"

[theme]
base = "light"
primaryColor = "#1D4ED8"
backgroundColor = "#F7FAFF"
secondaryBackgroundColor = "#EAF2FF"
textColor = "#172033"
